// suggestions.js

export const CURATED_SUGGESTIONS = [
  // Vlorë & North
  {
    name: "Apollonia Archaeological Park",
    lat: 40.7214,
    lng: 19.4678,
    icon: "landmark",
    type: "attraction",
    desc: "Ancient Greek city ruins. A must-see historical site before hitting the coastal mountains.",
  },
  {
    name: "Zvërnec Monastery",
    lat: 40.5186,
    lng: 19.4022,
    icon: "landmark",
    type: "attraction",
    desc: "13th-century Byzantine monastery on a tiny island, reached by a long wooden bridge.",
  },
  {
    name: "Radhimë Beach",
    lat: 40.3667,
    lng: 19.4833,
    icon: "footprints",
    type: "main",
    desc: "Great pebble beaches and seafood restaurants right before the Llogara ascent.",
  },

  // Llogara & Dhërmi Area
  {
    name: "Llogara Pass Viewpoint",
    lat: 40.1931,
    lng: 19.5969,
    icon: "flag",
    type: "main",
    desc: "The highest point on the coastal highway. Pull over for an incredible panorama of the Ionian Sea.",
  },
  {
    name: "Llogara National Park",
    lat: 40.2017,
    lng: 19.5844,
    icon: "footprints",
    type: "attraction",
    desc: "Dense pine forests. Great for a quick cool-down hike; you can often see wild deer.",
  },
  {
    name: "Palasë Beach",
    lat: 40.165,
    lng: 19.596,
    icon: "footprints",
    type: "main",
    desc: "The first major beach after descending Llogara. Massive, white stones and blue water.",
  },
  {
    name: "Drymades Beach",
    lat: 40.1583,
    lng: 19.6102,
    icon: "coffee",
    type: "main",
    desc: "Slightly trendier than Dhërmi. Known for great beach clubs, sunsets, and a split pebble/sand beach.",
  },
  {
    name: "Dhërmi Old Town",
    lat: 40.1517,
    lng: 19.6418,
    icon: "landmark",
    type: "attraction",
    desc: "Wander the hillside cobblestones up to the Monastery of St. Mary for epic views.",
  },

  // Vuno, Gjipe & Himarë
  {
    name: "Gjipe Beach",
    lat: 40.1264,
    lng: 19.6732,
    icon: "footprints",
    type: "attraction",
    desc: "Reddit's favorite hidden beach. Reached only by a 30-min hike down a spectacular red-rock canyon.",
  },
  {
    name: "Vuno Village",
    lat: 40.1397,
    lng: 19.6947,
    icon: "coffee",
    type: "attraction",
    desc: "Historic hillside village. Grab a coffee on the highway and walk the steep alleys.",
  },
  {
    name: "Jalë Beach (Jala)",
    lat: 40.1189,
    lng: 19.6997,
    icon: "footprints",
    type: "main",
    desc: "Vibrant water color, very popular with youth and campers. Great day-party vibe in summer.",
  },
  {
    name: "Livadhi Beach",
    lat: 40.1086,
    lng: 19.7214,
    icon: "footprints",
    type: "main",
    desc: "A long, wide, relaxed beach just north of Himarë. Less crowded than the city center.",
  },
  {
    name: "Kalaja e Himarës (Old Town)",
    lat: 40.1181,
    lng: 19.7333,
    icon: "landmark",
    type: "attraction",
    desc: "Castle ruins on the hill above modern Himarë. The best sunset views on the coast.",
  },
  {
    name: "Taverna Lefteri",
    lat: 40.103,
    lng: 19.7483,
    icon: "coffee",
    type: "main",
    desc: "Legendary local seafood in Himarë center. Consistently recommended by locals and tourists alike.",
  },

  // Porto Palermo, Qeparo & Borsh
  {
    name: "Porto Palermo Castle",
    lat: 40.0625,
    lng: 19.7911,
    icon: "landmark",
    type: "attraction",
    desc: "Explore Ali Pasha's triangular castle and see the massive Cold War submarine bunker across the bay.",
  },
  {
    name: "Qeparo Fshat (Old Qeparo)",
    lat: 40.0628,
    lng: 19.8275,
    icon: "landmark",
    type: "attraction",
    desc: "Half-abandoned, incredibly atmospheric stone village high up on the mountain. 10/10 exploration.",
  },
  {
    name: "Borsh Waterfall & Cafe",
    lat: 40.0583,
    lng: 19.8569,
    icon: "coffee",
    type: "attraction",
    desc: "Ujëvara e Borshit. A cafe literally built over running waterfalls under lush trees.",
  },
  {
    name: "Borsh Beach",
    lat: 40.0431,
    lng: 19.845,
    icon: "footprints",
    type: "main",
    desc: "The longest beach on the Ionian coast (7km). Very relaxed, spacious, and family-friendly.",
  },

  // The Deep South (Lukovë to Ksamil)
  {
    name: "Buneci Beach",
    lat: 40.0031,
    lng: 19.9242,
    icon: "footprints",
    type: "main",
    desc: "A quieter, lesser-known pebble beach divided by a small river. Great for escaping crowds.",
  },
  {
    name: "Lukova Beach",
    lat: 39.9833,
    lng: 19.925,
    icon: "footprints",
    type: "main",
    desc: "Stunning turquoise waters backed by terraced olive groves. A local favorite.",
  },
  {
    name: "Lëkurësi Castle",
    lat: 39.8661,
    lng: 20.0253,
    icon: "flag",
    type: "main",
    desc: "Overlooks the entire city of Sarandë and the island of Corfu. Go for golden hour/sunset.",
  },
  {
    name: "Pulëbardha Beach",
    lat: 39.7958,
    lng: 20.0039,
    icon: "footprints",
    type: "attraction",
    desc: 'Translation: "Seagull Beach". Dramatic cliffs, insanely clear water. Gets busy, so arrive early.',
  },
  {
    name: "Ksamil Islands",
    lat: 39.7725,
    lng: 19.995,
    icon: "footprints",
    type: "main",
    desc: "The 'Maldives of Europe'. Rent a paddleboard or swim out to the three small islands.",
  },
  {
    name: "Butrint National Park",
    lat: 39.7444,
    lng: 20.02,
    icon: "landmark",
    type: "attraction",
    desc: "UNESCO World Heritage site. Mind-blowing Greek, Roman, and Venetian ruins in a lush forest.",
  },

  // Inland Wonders
  {
    name: "The Blue Eye (Syri i Kaltër)",
    lat: 39.9236,
    lng: 20.1925,
    icon: "footprints",
    type: "attraction",
    desc: "A mesmerizing, freezing-cold natural spring bubbling up from a deep karst hole.",
  },
  {
    name: "Gjirokastër Old Bazaar",
    lat: 40.0738,
    lng: 20.1386,
    icon: "coffee",
    type: "attraction",
    desc: "The 'City of Stone'. Walk the incredible Ottoman-era bazaar and grab authentic byrek.",
  },
  {
    name: "Gjirokastër Castle",
    lat: 40.073,
    lng: 20.136,
    icon: "landmark",
    type: "attraction",
    desc: "One of the largest castles in the Balkans. Features a captured US spy plane on the roof!",
  },
];
